package com.personal.tmdb.core.util

object C {
    const val TMDB_BASE_URL = "https://api.themoviedb.org/"
    const val TMDB_IMAGES_BASE_URL = "https://image.tmdb.org/t/p/"
    const val GRAVATAR_IMAGES_BASE_URL = "https://gravatar.com/avatar/"
    const val REDIRECT_URL = "tmdb://auth/approved"
    const val APPROVED = "approved"
    const val BACKDROP_W1280 = "w1280"
    const val POSTER_W300 = "w300"
    const val POSTER_W154 = "w154"
    const val STILL_W300 = "w300"
    const val LOGO_W92 = "w92"
    const val PROFILE_W185 = "w185"
    const val MEDIA_ID = "mediaId"
    const val COLLECTION_ID = "collectionId"
    const val MEDIA_TYPE = "mediaType"
    const val SEARCH_TYPE = "searchType"
    const val SEARCH_QUERY = "searchQuery"
    const val MEDIA_NAME = "contentName"
    const val PERSON_ID = "personId"
    const val PERSON_NAME = "personName"
    const val SEASON_NUMBER = "seasonNumber"
    const val EPISODE_NUMBER = "episodeNumber"

    const val FACEBOOK = "https://www.facebook.com/%s"
    const val INSTAGRAM = "https://www.instagram.com/%s"
    const val TIKTOK = "https://www.tiktok.com/@%s"
    const val YOUTUBE = "https://www.youtube.com/%s"
    const val TWITTER_X = "https://x.com/%s"

    const val SHARE_MEDIA = "https://www.themoviedb.org/%s/%d"
    const val SHARE_CAST = "https://www.themoviedb.org/%s/%d/cast"
    const val SHARE_COLLECTION = "https://www.themoviedb.org/collection/%d"
    const val SHARE_SEASON = "https://www.themoviedb.org/tv/%d/season/%d"
    const val SHARE_EPISODE = "https://www.themoviedb.org/tv/%d/season/%d/episode/%d"
    const val SHARE_EPISODE_CAST = "https://www.themoviedb.org/tv/%d/season/%d/episode/%d/cast"
    const val SHARE_PERSON = "https://www.themoviedb.org/person/%d"
}