package com.personal.tmdb.core.util

object C {
    const val TMDB_BASE_URL = "https://api.themoviedb.org/"
    const val TMDB_IMAGES_BASE_URL = "https://image.tmdb.org/t/p/"
    const val GRAVATAR_IMAGES_BASE_URL = "https://gravatar.com/avatar/%s?s=185"
    const val FLAG_ICONS_URL = "https://flagicons.lipis.dev/flags/4x3/%s.svg"
    const val PRIMARY_LANG = "af,ar,be,bg,bn,br,ca,ch,cs,cy,da,de,el,en,eo,es,et,eu,fa,fi,fr,ga,gd,gl,he,hi,hr,hu,id,it,ja,ka,kk,kn,ko,ku,ky,lt,lv,ml,mr,ms,nb,nl,no,pa,pl,pt,ro,ru,si,sk,sl,so,sq,sr,sv,sw,ta,te,th,tl,tr,uk,ur,uz,vi,zh,zu"
    const val REDIRECT_URL = "tmdb://auth/approved"
    const val ORIGINAL = "original"
    const val BACKDROP_W1280 = "w1280"
    const val BACKDROP_W780 = "w780"
    const val POSTER_W300 = "w300"
    const val POSTER_W154 = "w154"
    const val STILL_W300 = "w300"
    const val LOGO_W92 = "w92"
    const val PROFILE_W185 = "w185"
    const val LOGO_W500 = "w500"
    const val MEDIA_ID = "mediaId"
    const val COLLECTION_ID = "collectionId"
    const val MEDIA_TYPE = "mediaType"
    const val MEDIA_NAME = "contentName"
    const val PERSON_ID = "personId"
    const val PERSON_NAME = "personName"
    const val SEASON_NUMBER = "seasonNumber"
    const val EPISODE_NUMBER = "episodeNumber"
    const val IMAGES_PATH = "imagesPath"
    const val IMAGE_INDEX = "imageIndex"
    const val IMAGE_TYPE = "imageType"
    const val REVIEW = "review%d"

    const val FACEBOOK = "https://www.facebook.com/%s"
    const val INSTAGRAM = "https://www.instagram.com/%s"
    const val TIKTOK = "https://www.tiktok.com/@%s"
    const val YOUTUBE = "https://www.youtube.com/%s"
    const val TWITTER_X = "https://x.com/%s"
    const val JUSTWATCH_URL = "https://www.justwatch.com/"

    const val SHARE_MEDIA = "https://www.themoviedb.org/%s/%d"
    const val SHARE_CAST = "https://www.themoviedb.org/%s/%d/cast"
    const val SHARE_COLLECTION = "https://www.themoviedb.org/collection/%d"
    const val SHARE_SEASON = "https://www.themoviedb.org/tv/%d/season/%d"
    const val SHARE_EPISODE = "https://www.themoviedb.org/tv/%d/season/%d/episode/%d"
    const val SHARE_EPISODE_CAST = "https://www.themoviedb.org/tv/%d/season/%d/episode/%d/cast"
    const val SHARE_PERSON = "https://www.themoviedb.org/person/%d"
    const val SHARE_IMAGE = "https://image.tmdb.org/t/p/original%s"

    const val MEDIA_IMAGES = "%s/%d/images"
    const val EPISODE_MEDIA_IMAGES = "tv/%d/season/%d/episode/%d/images"

    const val GITHUB_PROJECT = "https://github.com/Avvami/TMDB"
    const val TMDB_SUPPORT_FORUMS = "https://www.themoviedb.org/talk"
    const val TMDB_PRIVACY_POLICY = "https://www.themoviedb.org/privacy-policy"
}